language: python
python:
  - "2.7"
sudo: false
install:
  - "pip install -r requirements.txt"
  - "make ci"
before_script:
script: ansible-playbook test-consul.yml
after_failure:
  - "killall consul"
after_success:
  - "killall consul"
