#!/usr/bin/env bash
#
# Install and set up consul to run server for tests
#

CONSUL_VER=0.5.0
CONSUL_DL_URL=https://dl.bintray.com/mitchellh/consul/${CONSUL_VER}_$(uname -s)_$(uname -m).zip

curl -L $CONSUL_DL_URL > ./consul
chmod +x ./consul

export PATH=$PWD:$PATH
consul agent --server=true --bootstrap-expect=1 --data-dir=.

# vim: ft=sh:
